baseURL: https://musictide.pages.dev/
defaultContentLanguage: pt
defaultContentLanguageInSubdir: false
enableRobotsTXT: true
enableEmoji: true

module:
  hugoVersion:
    min: "0.141.0"
    extended: true

pagination:
  pagerSize: 100

imaging:
  anchor: Center

outputFormats:
  fragment:
    name: fragment
    baseName: fragment
    mediaType: text/html
    isHTML: true
    notAlternative: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
  term:
    - HTML
    - fragment

taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series

related:
  threshold: 0
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 100
    - name: series
      weight: 50
    - name: authors
      weight: 20
    - name: date
      weight: 10
      pattern: "200601"
