main:
  - name: Espinho
    url: /en/categories/espinho/
    weight: 10
  - name: Nacional
    url: /en/categories/nacional/
    weight: 20
  - name: Culture
    url: /en/categories/cultura/
    weight: 30
  - name: Sport
    url: /en/categories/desporto/
    weight: 40
  - name: Lifestyle
    url: /en/categories/lifestyle/
    weight: 50
  - name: Agenda
    url: /en/categories/agenda/
    weight: 60
