main:
  - name: Cultura
    url: /categories/cultura/
    weight: 10
  - name: Desporto
    url: /categories/desporto/
    weight: 20
  - name: Lifestyle
    url: /categories/lifestyle/
    weight: 30
  - name: Agenda
    url: /categories/agenda/
    weight: 40
  - name: Colaboradores
    url: /authors/
    weight: 50
