mediaBaseURL: https://pub-576ea11202f543d0bf28d36ef63d18ff.r2.dev

logo: logo_fixed.png
disableTextInHeader: true

defaultAppearance: dark
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: false

header:
  layout: fixed

# footer:
#   showMenu: false
#   showCopyright: true
#   showThemeAttribution: false
#   showAppearanceSwitcher: true
#   showScrollToTop: true

homepage:
  layout: hero

article:
  showDate: true
  showAuthor: false
  showReadingTime: false
  showWordCount: false
  showTableOfContents: false
  showEdit: false
  showTaxonomies: false
  showHero: true
  heroStyle: big

list:
  # showHero: false
  # heroStyle: big
  # showCards: false
  showTableOfContents: false
  showSummary: true
  summaryLength: 0
