mediaBaseURL: https://pub-576ea11202f543d0bf28d36ef63d18ff.r2.dev

colorScheme: blowfish
defaultAppearance: dark
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: false

header:
  layout: basic

footer:
  showMenu: false
  showCopyright: true
  showThemeAttribution: false
  showAppearanceSwitcher: true
  showScrollToTop: true

homepage:
  layout: page
  showRecent: true
  showRecentItems: 9
  cardView: true
  showMoreLink: true
  showMoreLinkDest: /posts/

article:
  showDate: true
  showAuthor: false
  showReadingTime: true
  showWordCount: false
  showTableOfContents: false
  showEdit: false
  showTaxonomies: true

list:
  showCards: true
  showTableOfContents: false
  showSummary: true
